from __future__ import annotations

from typing import Any


def build_telemetry(
    *,
    device_id: str,
    user_agent: str,
    timestamp_ms: int,
    language: str,
) -> dict[str, Any]:
    app_version = user_agent.removeprefix("Mozilla/")
    return {
        "navigator": {
            "appCodeName": "Mozilla",
            "appMinorVersion": "undefined",
            "appName": "Netscape",
            "appVersion": app_version,
            "buildID": "undefined",
            "doNotTrack": "null",
            "msDoNotTrack": "undefined",
            "oscpu": "undefined",
            "platform": "MacIntel",
            "product": "Gecko",
            "productSub": "20030107",
            "cpuClass": "undefined",
            "vendor": "Google Inc.",
            "vendorSub": "",
            "deviceMemory": "32",
            "language": language,
            "systemLanguage": "undefined",
            "userLanguage": "undefined",
            "webdriver": "false",
            "userAgent": user_agent,
            "pdfViewerEnabled": "true",
            "hardwareConcurrency": 10,
            "maxTouchPoints": 0,
            "cookieEnabled": 1,
            "vibrate": 3,
            "credentials": 99,
            "storage": 99,
            "requestMediaKeySystemAccess": 3,
            "bluetooth": 99,
            "languages": f"{language},zh" if language.startswith("zh") else f"{language},en",
            "online": "true",
            "touchEvent": 2,
            "touchstart": 2,
        },
        "wID": {
            "nativeLength": 33,
            "nativeName": 2,
            "jsFontsList": "7c08003",
            "syntaxError": "-1",
            "timestamp": str(timestamp_ms),
            "timezone": 8,
            "canvas": "2363850128",
            "jsv": "",
            "browserType": 16,
            "iframe": 2,
            "pppt": 2,
            "rtt": 2,
            "sdkVersion": "5.3.0",
            "scmVersion": "2.0.0.507",
            "aid": 1988,
            "msgType": 1,
            "privacyMode": 514,
            "aidList": [1988, 368462],
            "aN": "1111111",
            "seq": [1, 1],
            "propLength": {"a": 1273, "b": 1233, "c": 1022, "d": 9, "e": 1025, "f": 0},
            "objProx": "11111111111111111",
            "sri": 2,
            "dups": 1,
            "hl": 2,
            "tz": "Asia/Shanghai",
            "tzS": "latn",
            "tzC": "gregory",
            "tzL": language,
            "iframeInfo": {
                "iFrameNP": {
                    "uA": user_agent,
                    "platform": "MacIntel",
                    "hC": 10,
                    "lang": language,
                    "wd": "false",
                },
                "iFrameSP": {"aH": 1125, "aW": 1800, "h": 1169, "w": 1800, "pD": 30},
                "propHash": "-263095343993",
            },
            "bb": {"a": 966, "b": 925, "c": 1},
            "aFP": "1038527147",
            "intP": 1.1459861526630101e23,
            "intPS": "1.1459861526630101e+23",
            "deb": 1,
            "ecdp": 1,
            "dFP": {
                "html": 1,
                "head": 1,
                "meta": 3,
                "title": 1,
                "script": 98,
                "link": 77,
                "style": 7,
                "body": 1,
                "svg": 3,
                "div": 104,
                "img": 1,
                "path": 3,
                "a": 1,
                "mxD": 15,
                "mdD": 3,
                "tE": 318,
                "oT": ["plasmo-csui", "span", "h1", "h2", "circle", "h3", "strong", "p"],
            },
            "reqM": {
                "totalXHRRequests": 30,
                "totalFetchRequests": 19,
                "interceptedXHRRequests": 0,
                "interceptedFetchRequests": 11,
            },
            "nap": "01311044241322244122",
            "permState": "prompt",
            "rtcIP": "",
            "index": 48,
        },
        "webgl": {
            "supportedExtensions": [
                "ANGLE_instanced_arrays",
                "EXT_blend_minmax",
                "EXT_clip_control",
                "EXT_color_buffer_half_float",
                "EXT_depth_clamp",
                "EXT_disjoint_timer_query",
                "EXT_float_blend",
                "EXT_frag_depth",
                "EXT_polygon_offset_clamp",
                "EXT_shader_texture_lod",
                "EXT_texture_compression_bptc",
                "EXT_texture_compression_rgtc",
                "EXT_texture_filter_anisotropic",
                "EXT_texture_mirror_clamp_to_edge",
                "EXT_sRGB",
                "KHR_parallel_shader_compile",
                "OES_element_index_uint",
                "OES_fbo_render_mipmap",
                "OES_standard_derivatives",
                "OES_texture_float",
                "OES_texture_float_linear",
                "OES_texture_half_float",
                "OES_texture_half_float_linear",
                "OES_vertex_array_object",
                "WEBGL_blend_func_extended",
                "WEBGL_color_buffer_float",
                "WEBGL_compressed_texture_astc",
                "WEBGL_compressed_texture_etc",
                "WEBGL_compressed_texture_etc1",
                "WEBGL_compressed_texture_pvrtc",
                "WEBGL_compressed_texture_s3tc",
                "WEBGL_compressed_texture_s3tc_srgb",
                "WEBGL_debug_renderer_info",
                "WEBGL_debug_shaders",
                "WEBGL_depth_texture",
                "WEBGL_draw_buffers",
                "WEBGL_lose_context",
                "WEBGL_multi_draw",
                "WEBGL_polygon_mode",
            ],
            "antialias": 1,
            "blueBits": 8,
            "depthBits": 24,
            "greenBits": 8,
            "maxAnisotropy": 16,
            "maxCombinedTextureImageUnits": 32,
            "maxCubeMapTextureSize": 16384,
            "maxFragmentUniformVectors": 1024,
            "maxRenderbufferSize": 16384,
            "maxTextureImageUnits": 16,
            "maxTextureSize": 16384,
            "maxVaryingVectors": 30,
            "maxVertexAttribs": 16,
            "maxVertexTextureImageUnits": 16,
            "maxVertexUniformVectors": 1024,
            "shadingLanguageVersion": "WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)",
            "stencilBits": 0,
            "version": "WebGL 1.0 (OpenGL ES 2.0 Chromium)",
            "vendor": "Google Inc. (Apple)",
            "renderer": "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Max, Unspecified Version)",
        },
        "plugins": {
            "plugin": [
                "internal-pdf-viewer|application/pdf|pdf",
                "internal-pdf-viewer|text/pdf|pdf",
                "internal-pdf-viewer|application/pdf|pdf",
                "internal-pdf-viewer|text/pdf|pdf",
                "internal-pdf-viewer|application/pdf|pdf",
                "internal-pdf-viewer|text/pdf|pdf",
                "internal-pdf-viewer|application/pdf|pdf",
                "internal-pdf-viewer|text/pdf|pdf",
                "internal-pdf-viewer|application/pdf|pdf",
                "internal-pdf-viewer|text/pdf|pdf",
            ],
            "pv": "0",
            "proto": 1,
        },
        "msgMeta": {
            "msgType": 1,
            "msgSrcProp": 1,
            "msgProtocol": 1,
            "aid": 1988,
            "aidList": [1988, 368462],
        },
        "customInit": {"ttwid": device_id},
    }
